version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    # environment:
    #   RABBITMQ_ERLANG_COOKIE: "secret cookie here"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

